name: Update Dojo

on: 
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: pwncollege/dojo-update@v1
        with:
          dojo: example~6c5fcc86
          update_code: https://pwn.college/dojo/example~6c5fcc86/update/254a8db77a98d864df4311cacf8026b1
